# Generated by Django 5.0.6 on 2024-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('pageCount', models.IntegerField(blank=True, null=True)),
                ('publishedDate', models.DateTimeField(blank=True, null=True)),
                ('thumbnailUrl', models.URLField(blank=True)),
                ('shortDescription', models.TextField(blank=True)),
                ('longDescription', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('categories', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
