# Generated by Django 5.0.6 on 2024-07-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_feedback_delete_user_author_unique_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='unique_author_name',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name',
        ),
    ]
