# Generated by Django 5.0.6 on 2024-07-12 14:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumbnailUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='G:\\PythonProjects\\REST_API_online_store\\media'), upload_to='book_images'),
        ),
    ]
